name: build-ios-app
on:
  push:

jobs:
  build:
    strategy:
      matrix:
        # xcode: ["13.4", "14.2"]
        xcode: ["12.5.1"]
    env:
      DEST: iPhone 8,OS=14.5

    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: (XCode ${{ matrix.xcode }} ) Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.PROVISION_PROFILE }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64"
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          ls -la $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64"
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          ls -la $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          ls -la $KEYCHAIN_PATH
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          ls -la $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
          xcode-select -p
          security find-identity -v -p codesigning
          xcodebuild clean -workspace Repro65.xcworkspace -scheme "Repro65" -destination "platform=sss"

      - run: |
          xcodebuild clean -workspace Repro65.xcworkspace -scheme "Repro65" -destination "platform=iOS $DEST"

      - run: |
          xcodebuild build -workspace Repro65.xcworkspace -scheme "Repro65" -destination "platform=iOS $DEST"

      - run: |
          xcodebuild test -workspace Repro65.xcworkspace -scheme "Repro65" -destination "platform=iOS $DEST"
